services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - /root/mnt/uptime_kuma/data:/app/data
    expose:
      # <Host Port>:<Container Port>
      - 3001
    restart: unless-stopped
    networks:
      - proxy_network
networks:
  proxy_network:
    external: true